# Generated by Django 2.2.5 on 2019-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(db_index=True, max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('nomer', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
